-- V013: 휴가/외근 신청 알림 타입을 notifications 체크 제약에 추가

ALTER TABLE notifications DROP CONSTRAINT chk_notification_type;
ALTER TABLE notifications ADD CONSTRAINT chk_notification_type CHECK (type IN (
    'CHANGE_REQUEST_SUBMITTED','CHANGE_REQUEST_APPROVED','CHANGE_REQUEST_REJECTED',
    'LEAVE_REQUEST_SUBMITTED','LEAVE_REQUEST_APPROVED','LEAVE_REQUEST_REJECTED',
    'OUTSIDE_WORK_REQUEST_SUBMITTED','OUTSIDE_WORK_REQUEST_APPROVED','OUTSIDE_WORK_REQUEST_REJECTED',
    'ATTENDANCE_CORRECTED','ATTENDANCE_CLOSED','ATTENDANCE_REOPENED','GENERAL'
));
