package com.attendance.notification.domain;

public enum NotificationType {
    CHANGE_REQUEST_SUBMITTED,
    CHANGE_REQUEST_APPROVED,
    CHANGE_REQUEST_REJECTED,
    LEAVE_REQUEST_SUBMITTED,
    LEAVE_REQUEST_APPROVED,
    LEAVE_REQUEST_REJECTED,
    OUTSIDE_WORK_REQUEST_SUBMITTED,
    OUTSIDE_WORK_REQUEST_APPROVED,
    OUTSIDE_WORK_REQUEST_REJECTED,
    WORKPLACE_CHANGE_REQUEST_SUBMITTED,
    WORKPLACE_CHANGE_REQUEST_APPROVED,
    WORKPLACE_CHANGE_REQUEST_REJECTED,
    WORK_SCHEDULE_CHANGE_REQUEST_SUBMITTED,
    WORK_SCHEDULE_CHANGE_REQUEST_APPROVED,
    WORK_SCHEDULE_CHANGE_REQUEST_REJECTED,
    ATTENDANCE_CORRECTED,
    ATTENDANCE_CLOSED,
    ATTENDANCE_REOPENED,
    GENERAL
}
